#' Path to the outputs generated by the model
#'
#' @include enum.R
#' @export
OutputPaths <- enum(list(
  Aciclovir_PVB = "Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood)"
))
