# Excel ↔ JSON bridge: internal helpers ----

#' Parse parameter sheets from an Excel file into JSON structure
#' @param filePath Path to the Excel file
#' @param sheetNames Sheets to read. If NULL, reads all sheets.
#' @param schemaVersion Project structure schema version. Used to adapt parsing
#'   logic when importing Excel files generated by an older schema.
#' @returns Named list of parameter arrays
#' @keywords internal
#' @noRd
.parseExcelParameterSheets <- function(
  filePath,
  sheetNames = NULL,
  schemaVersion = "2.0"
) {
  if (is.null(sheetNames)) {
    sheetNames <- readxl::excel_sheets(filePath)
  }
  result <- list()
  for (sheet in sheetNames) {
    df <- readExcel(filePath, sheet = sheet)
    entries <- list()
    if (nrow(df) > 0) {
      for (i in seq_len(nrow(df))) {
        entry <- list(
          containerPath = as.character(df[["Container Path"]][[i]]),
          parameterName = as.character(df[["Parameter Name"]][[i]]),
          value = as.numeric(df[["Value"]][[i]]),
          units = if (is.na(df[["Units"]][[i]]) || df[["Units"]][[i]] == "") {
            NULL
          } else {
            as.character(df[["Units"]][[i]])
          }
        )
        entries[[i]] <- entry
      }
    }
    result[[sheet]] <- entries
  }
  result
}

#' Parse Scenarios Excel sheet into JSON structure
#' @param scenarioDf Data frame from the Scenarios sheet
#' @param schemaVersion Project structure schema version. Used to adapt parsing
#'   logic when importing Excel files generated by an older schema.
#' @returns List of scenario objects
#' @keywords internal
#' @noRd
.parseExcelScenarios <- function(scenarioDf, schemaVersion = "2.0") {
  scenarios <- list()
  for (i in seq_len(nrow(scenarioDf))) {
    row <- scenarioDf[i, ]
    scenario <- list(
      name = as.character(row$Scenario_name),
      individualId = .naToNull(as.character(row$IndividualId)),
      populationId = .naToNull(as.character(row$PopulationId)),
      readPopulationFromCSV = .naToNull(as.logical(row$ReadPopulationFromCSV)),
      modelParameters = .parseCommaListToArray(row$ModelParameterSheets),
      applicationProtocol = .naToNull(as.character(row$ApplicationProtocol)),
      simulationTime = .naToNull(as.character(row$SimulationTime)),
      simulationTimeUnit = .naToNull(as.character(row$SimulationTimeUnit)),
      steadyState = .naToNull(as.logical(row$SteadyState)),
      steadyStateTime = .naToNull(as.numeric(row$SteadyStateTime)),
      steadyStateTimeUnit = .naToNull(as.character(row$SteadyStateTimeUnit)),
      overwriteFormulasInSS = .naToNull(as.logical(row$OverwriteFormulasInSS)),
      modelFile = as.character(row$ModelFile),
      outputPathIds = .parseCommaListToArray(row$OutputPathsIds)
    )
    scenarios[[i]] <- scenario
  }
  scenarios
}

#' Parse IndividualBiometrics Excel sheet into JSON structure
#' @param indivDf Data frame from the IndividualBiometrics sheet
#' @param schemaVersion Project structure schema version. Used to adapt parsing
#'   logic when importing Excel files generated by an older schema.
#' @returns List of individual objects
#' @keywords internal
#' @noRd
.parseExcelIndividuals <- function(indivDf, schemaVersion = "2.0") {
  individuals <- list()
  for (i in seq_len(nrow(indivDf))) {
    row <- indivDf[i, ]
    indiv <- list(
      individualId = as.character(row$IndividualId),
      species = as.character(row$Species),
      population = as.character(row$Population),
      gender = as.character(row$Gender),
      weight = .naToNull(as.numeric(row$`Weight [kg]`)),
      height = .naToNull(as.numeric(row$`Height [cm]`)),
      age = .naToNull(as.numeric(row$`Age [year(s)]`)),
      proteinOntogenies = .naToNull(as.character(row$`Protein Ontogenies`))
    )
    individuals[[i]] <- indiv
  }
  individuals
}

#' Parse Populations Excel sheet into JSON structure
#' @param popDf Data frame from the Demographics sheet
#' @param schemaVersion Project structure schema version. Used to adapt parsing
#'   logic when importing Excel files generated by an older schema.
#' @returns List of population objects
#' @keywords internal
#' @noRd
.parseExcelPopulations <- function(popDf, schemaVersion = "2.0") {
  populations <- list()
  for (i in seq_len(nrow(popDf))) {
    row <- popDf[i, ]
    pop <- list(
      populationId = as.character(row$PopulationName),
      species = as.character(row$species),
      population = as.character(row$population),
      numberOfIndividuals = .naToNull(as.numeric(row$numberOfIndividuals)),
      proportionOfFemales = .naToNull(as.numeric(row$proportionOfFemales)),
      weightMin = .naToNull(as.numeric(row$weightMin)),
      weightMax = .naToNull(as.numeric(row$weightMax)),
      weightUnit = .naToNull(as.character(row$weightUnit)),
      heightMin = .naToNull(as.numeric(row$heightMin)),
      heightMax = .naToNull(as.numeric(row$heightMax)),
      heightUnit = .naToNull(as.character(row$heightUnit)),
      ageMin = .naToNull(as.numeric(row$ageMin)),
      ageMax = .naToNull(as.numeric(row$ageMax)),
      BMIMin = .naToNull(as.numeric(row$BMIMin)),
      BMIMax = .naToNull(as.numeric(row$BMIMax)),
      BMIUnit = .naToNull(as.character(row$BMIUnit)),
      proteinOntogenies = .naToNull(as.character(row$`Protein Ontogenies`))
    )
    populations[[i]] <- pop
  }
  populations
}

#' Parse Plots Excel file into JSON structure
#' @param plotsFile Path to the Plots.xlsx file
#' @param schemaVersion Project structure schema version. Used to adapt parsing
#'   logic when importing Excel files generated by an older schema.
#' @returns Named list with dataCombined, plotConfiguration, plotGrids,
#'   exportConfiguration
#' @keywords internal
#' @noRd
.parseExcelPlots <- function(plotsFile, schemaVersion = "2.0") {
  sheets <- readxl::excel_sheets(plotsFile)
  result <- list()
  for (sheet in sheets) {
    df <- readExcel(plotsFile, sheet = sheet)
    if (nrow(df) == 0) {
      result[[sheet]] <- list()
      next
    }
    entries <- list()
    for (i in seq_len(nrow(df))) {
      entry <- list()
      for (col in names(df)) {
        val <- df[[col]][[i]]
        entry[[col]] <- .naToNull(val)
      }
      entries[[i]] <- entry
    }
    result[[sheet]] <- entries
  }
  result
}

#' Convert parameter structures to Excel sheet data frames
#' @param parameterGroups Named list of parameter structures (paths, values,
#'   units)
#' @returns Named list of data frames suitable for Excel sheets
#' @keywords internal
#' @noRd
.parameterStructuresToExcelSheets <- function(parameterGroups) {
  sheets <- list()
  for (name in names(parameterGroups)) {
    params <- parameterGroups[[name]]
    if (is.null(params) || length(params$paths) == 0) {
      sheets[[name]] <- data.frame(
        `Container Path` = character(0),
        `Parameter Name` = character(0),
        Value = numeric(0),
        Units = character(0),
        check.names = FALSE,
        stringsAsFactors = FALSE
      )
      next
    }
    splitPaths <- lapply(
      params$paths,
      .splitParameterPathIntoContainerAndName
    )
    sheets[[name]] <- data.frame(
      `Container Path` = vapply(
        splitPaths,
        function(x) x$containerPath,
        character(1)
      ),
      `Parameter Name` = vapply(
        splitPaths,
        function(x) x$parameterName,
        character(1)
      ),
      Value = params$values,
      Units = params$units,
      check.names = FALSE,
      stringsAsFactors = FALSE
    )
  }
  sheets
}

#' Convert individuals data to an IndividualBiometrics data frame
#' @param individuals Named list of IndividualCharacteristics objects
#' @returns A data frame
#' @keywords internal
#' @noRd
.individualsToExcelDf <- function(individuals) {
  rows <- list()
  for (indivId in names(individuals)) {
    ic <- individuals[[indivId]]
    ontoStr <- ic$proteinOntogenies %||% NA

    rows[[length(rows) + 1]] <- data.frame(
      IndividualId = indivId,
      Species = as.character(ic$species),
      Population = as.character(ic$population %||% NA),
      Gender = as.character(ic$gender),
      `Weight [kg]` = as.double(ic$weight %||% NA),
      `Height [cm]` = as.double(ic$height %||% NA),
      `Age [year(s)]` = as.double(ic$age %||% NA),
      `Protein Ontogenies` = ontoStr,
      check.names = FALSE,
      stringsAsFactors = FALSE
    )
  }
  do.call(rbind, rows)
}

#' Convert populations data to an Excel data frame
#' @param populations Named list of PopulationCharacteristics objects
#' @returns A data frame
#' @keywords internal
#' @noRd
.populationsToExcelDf <- function(populations) {
  rows <- list()
  for (popId in names(populations)) {
    popData <- populations[[popId]]
    ontoStr <- popData$proteinOntogenies %||% NA

    rows[[length(rows) + 1]] <- data.frame(
      PopulationName = popId,
      species = as.character(popData$species),
      population = as.character(popData$population %||% NA),
      numberOfIndividuals = as.double(popData$numberOfIndividuals %||% NA),
      proportionOfFemales = as.double(popData$proportionOfFemales %||% NA),
      weightMin = as.double(popData$weightMin %||% NA),
      weightMax = as.double(popData$weightMax %||% NA),
      weightUnit = as.character(popData$weightUnit %||% NA),
      heightMin = as.double(popData$heightMin %||% NA),
      heightMax = as.double(popData$heightMax %||% NA),
      heightUnit = as.character(popData$heightUnit %||% NA),
      ageMin = as.double(popData$ageMin %||% NA),
      ageMax = as.double(popData$ageMax %||% NA),
      BMIMin = as.double(popData$BMIMin %||% NA),
      BMIMax = as.double(popData$BMIMax %||% NA),
      BMIUnit = as.character(popData$BMIUnit %||% NA),
      `Protein Ontogenies` = ontoStr,
      check.names = FALSE,
      stringsAsFactors = FALSE
    )
  }
  do.call(rbind, rows)
}

#' Convert Scenario objects to an Excel data frame
#' @param scenarioConfigs Named list of Scenario objects
#' @param outputPaths Named character vector of output paths (names are IDs,
#'   values are path strings) from `Project$outputPaths`.
#'   Used to reverse-lookup scenario output paths back to IDs.
#' @returns A data frame
#' @keywords internal
#' @noRd
.scenarioConfigurationsToExcelDf <- function(
  scenarioConfigs,
  outputPaths = NULL
) {
  rows <- list()
  for (name in names(scenarioConfigs)) {
    sc <- scenarioConfigs[[name]]
    paramGroupNames <- sc$modelParameters
    paramGroupsStr <- if (
      !is.null(paramGroupNames) && length(paramGroupNames) > 0
    ) {
      paste(paramGroupNames, collapse = ", ")
    } else {
      NA
    }
    # simulationTime → string representation
    simTimeStr <- NA
    if (!is.null(sc$simulationTime)) {
      intervals <- vapply(
        sc$simulationTime,
        function(interval) {
          paste(interval, collapse = ", ")
        },
        character(1)
      )
      simTimeStr <- paste(intervals, collapse = "; ")
    }
    # outputPaths → reverse-lookup IDs from project$outputPaths
    outputPathIdsStr <- NA
    if (!is.null(sc$outputPaths) && !is.null(outputPaths)) {
      matchedIds <- names(outputPaths)[match(sc$outputPaths, outputPaths)]
      matchedIds <- matchedIds[!is.na(matchedIds)]
      if (length(matchedIds) > 0) {
        outputPathIdsStr <- paste(matchedIds, collapse = ", ")
      }
    }

    # Reconstruct steadyStateTime back to the original unit
    ssTime <- NA
    ssTimeUnit <- NA
    if (
      !is.null(sc$steadyStateTime) &&
        !is.na(sc$steadyStateTime) &&
        sc$steadyStateTime > 0
    ) {
      ssTimeUnit <- sc$steadyStateTimeUnit %||% "min"
      ssTime <- ospsuite::toUnit(
        quantityOrDimension = ospDimensions$Time,
        values = sc$steadyStateTime,
        targetUnit = ssTimeUnit
      )
    }

    rows[[length(rows) + 1]] <- data.frame(
      Scenario_name = sc$scenarioName,
      IndividualId = sc$individualId %||% NA,
      PopulationId = if (sc$simulationType == "Population") {
        sc$populationId
      } else {
        NA
      },
      ReadPopulationFromCSV = sc$readPopulationFromCSV %||% FALSE,
      ModelParameterSheets = paramGroupsStr,
      ApplicationProtocol = sc$applicationProtocol %||% NA,
      SimulationTime = simTimeStr,
      SimulationTimeUnit = sc$simulationTimeUnit %||% NA,
      SteadyState = sc$simulateSteadyState %||% FALSE,
      SteadyStateTime = ssTime,
      SteadyStateTimeUnit = ssTimeUnit,
      OverwriteFormulasInSS = sc$overwriteFormulasInSS %||% FALSE,
      ModelFile = sc$modelFile %||% NA,
      OutputPathsIds = outputPathIdsStr,
      check.names = FALSE,
      stringsAsFactors = FALSE
    )
  }
  do.call(rbind, rows)
}

#' Extract private .filePathsData from a Project
#' @param project Project object
#' @returns Named list of property data
#' @keywords internal
#' @noRd
.extractFilePathsData <- function(project) {
  project$.getFilePathsData()
}

#' Convert NA to NULL for JSON serialization
#' @keywords internal
#' @noRd
.naToNull <- function(x) {
  if (is.null(x) || length(x) == 0) {
    return(NULL)
  }
  if (length(x) == 1L && is.na(x)) {
    return(NULL)
  }
  x
}

#' Parse a comma-separated string into a character vector, or NULL
#' @keywords internal
#' @noRd
.parseCommaListToArray <- function(x) {
  if (is.null(x) || length(x) == 0 || is.na(x) || x == "") {
    return(NULL)
  }
  parts <- trimws(strsplit(as.character(x), ",", fixed = TRUE)[[1]])
  parts[nzchar(parts)]
}
