name: test-pkg-and-coverage

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]
  workflow_dispatch:

jobs:
  test-pkg-and-coverage:
    uses: Open-Systems-Pharmacology/Workflows/.github/workflows/test-pkg-and-coverage.yaml@main
    with:
      install-pksim: true
      install-rClr: true
      rClr-version: '0.9.2'
      extra-packages: |
        ospsuite.utils=github::Open-Systems-Pharmacology/OSPSuite.RUtils
        tlf=github::Open-Systems-Pharmacology/TLF-Library
        ospsuite=github::Open-Systems-Pharmacology/OSPSuite-R
        ospsuite.parameteridentification=github::Open-Systems-Pharmacology/OSPSuite.ParameterIdentification
